# Generated by Django 5.0.6 on 2024-05-14 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('descrioption', models.TextField(blank=True)),
                ('technology', models.CharField(max_length=30)),
                ('date_pub', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
